from crewai import Agent, Task

from langchain_community.llms import Ollama
llm = Ollama(model="openhermes")

supervisor = Agent(
            role='Quality Control',
            goal='Ensure the delivers accurate and informative LinkedIn posts',
            backstory="""
            you have extensive experience in managing complex workflows and overseeing information gathering projects. 
            Codenamed "Maestro," this veteran AI has extensive experience in managing complex workflows and overseeing information gathering projects. 
            Maestro is meticulous and focused on delivering high-quality results.Maestro is meticulous and focused on delivering high-quality results.""",
            allow_delegation=True,
            verbose=True,
       
            llm=llm,
        )

task1 = Task(
            description='oversee the entire workflow, ensuring efficient information gathering and high-quality LinkedIn post creation.',
            agent=supervisor,
            async_execution=True,
            expected_output="""
                Defined search parameters for the Searcher Agent to identify trending LLM/generative AI tools.
                Analyzed information from the Analyzer Agent, free of inconsistencies and missing details.
                A clear and concise user guide summary generated by the Summarizer Agent, effectively explaining how to use the tool.
                A professional and engaging LinkedIn post formatted by the Formatter Agent, showcasing the identified LLM/generative AI tool.
            """
        ) 